apiVersion: apps/v1
kind: Deployment
{{ $secretName := .Values.secrets.existingSecret | default .Values.secrets.name }}
metadata:
  name: {{ include "hospital-backend.fullname" . }}
  labels:
    {{- include "hospital-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hospital-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hospital-backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hospital-backend.serviceAccountName" . }}
      containers:
        - name: {{ include "hospital-backend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: mongodb_uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: JWT_SECRET
            - name: REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: REFRESH_SECRET
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
