[control]
116.206.83.75 ansible_user=num_hospital ansible_password={{ prod_ssh_password }} ansible_become=true ansible_become_method=sudo ansible_become_pass={{ prod_ssh_password }}

[workers]
# Single node — control plane runs workloads too

[all:children]
control
workers
