replicaCount: 1

image:
  repository: nurlan123/hospital-front-end
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullNameOverride: ""

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

env:
  nextPublicBackendUrl: /api

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "192Mi"
    cpu: "150m"

nodeSelector: {}

affinity: {}

tolerations: []
