apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer-registration-db.fullname" . }}
  labels:
    {{- include "customer-registration-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "customer-registration-db.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: postgres
