replicaCount: 1

image:
  repository: nurlannn/icd10-suggest-service
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullNameOverride: "icd10-suggest-service"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  icd10ApiUrl: "http://icd10-code-service.num.svc.cluster.local:8082/api/icd10"
  springDatasourceUrl: "jdbc:h2:file:/data/hospital_db"
  springH2ConsoleEnabled: "false"

dependencyWait:
  enabled: true
  image:
    repository: curlimages/curl
    tag: "8.7.1"
    pullPolicy: IfNotPresent
  timeoutSeconds: 300

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "384Mi"
    cpu: "300m"

strategy:
  type: Recreate

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

startupProbe:
  httpGet:
    path: /api/diagnosis/health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 18

livenessProbe:
  httpGet:
    path: /api/diagnosis/health
    port: http
  initialDelaySeconds: 90
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /api/diagnosis/health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10

nodeSelector: {}

affinity: {}

tolerations: []
