apiVersion: apps/v1
kind: Deployment
{{ $secretName := .Values.secrets.existingSecret | default .Values.secrets.name }}
metadata:
  name: {{ include "customer-registration.fullname" . }}
  labels:
    {{- include "customer-registration.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "customer-registration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "customer-registration.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "customer-registration.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.serverPort | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.springDatasourceUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: springDatasourceUsername
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: springDatasourcePassword
            - name: HOSPITAL_PUBLIC_KEY
              value: {{ .Values.env.hospitalPublicKey | quote }}
            - name: HOSPITAL_PRIVATE_KEY
              value: {{ .Values.env.hospitalPrivateKey | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
