{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "customer-registration.labels" . | nindent 4 }}
type: Opaque
stringData:
  springDatasourceUsername: {{ .Values.secrets.springDatasourceUsername | quote }}
  springDatasourcePassword: {{ .Values.secrets.springDatasourcePassword | quote }}
{{- end }}
