nameOverride: ""
fullNameOverride: ""

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  path: /
  gatewayService:
    name: hospital-gateway
    port: 80
