replicaCount: 1

image:
  repository: hospital-backend
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullNameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

containerPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  icd10SuggestBaseUrl: "http://icd10-suggest-service:8080/api"
  icd10SuggestTimeoutMs: "5000"
  customerRegistrationBaseUrl: "http://customer-registration:8081"

secrets:
  create: true
  name: hospital-secrets
  existingSecret: ""
  mongodb_uri: ""
  JWT_SECRET: ""
  REFRESH_SECRET: ""

nodeSelector:
  node-role: worker

affinity: {}

tolerations: []
