apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hospital-gateway.fullname" . }}-config
  labels:
    {{- include "hospital-gateway.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        client_max_body_size 10m;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Request-Id $request_id;

        proxy_connect_timeout 5s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;

        location = /gateway-health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "gateway-ok\n";
        }

        location = /api {
            return 301 /api/;
        }

        location / {
            proxy_pass http://{{ .Values.frontend.serviceName }}:{{ .Values.frontend.servicePort }};
            proxy_redirect off;
        }

        location /api/ {
            proxy_pass http://{{ .Values.backend.serviceName }}:{{ .Values.backend.servicePort }};
            proxy_redirect off;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        }
    }
