replicaCount: 1

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

nameOverride: ""
fullNameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

frontend:
  serviceName: hospital-frontend.num.svc.cluster.local
  servicePort: 3000

backend:
  serviceName: hospital-backend.num.svc.cluster.local
  servicePort: 8000
  authValidationPath: /api/auth/validate

resources:
  requests:
    memory: "32Mi"
    cpu: "25m"
  limits:
    memory: "96Mi"
    cpu: "100m"

nodeSelector: {}

affinity: {}

tolerations: []
