controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    enabled: true
    type: ClusterIP

  ingressClass: nginx

  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: k8s.io/ingress-nginx

  watchIngressWithoutClass: false

  publishService:
    enabled: false

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
    - key: node-role.kubernetes.io/master
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule

defaultBackend:
  enabled: true
