- hosts: servers
  become: yes

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -

    - name: Install helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash