name: Ansible Setup
run-name: "Ansible | ${{ github.event.inputs.target_env }} | ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Суулгах орчин"
        required: true
        type: choice
        options:
          - staging
          - prod

permissions:
  contents: read

jobs:
  setup-staging:
    if: github.event.inputs.target_env == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p "$HOME/.ssh"
          printf '%s\n' "${{ secrets.SERVER_SSH_KEY }}" | tr -d '\r' > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"

      - name: Add host keys
        run: |
          ssh-keyscan -T 10 -H 13.61.104.143 >> "$HOME/.ssh/known_hosts"
          ssh-keyscan -T 10 -H 13.61.2.126   >> "$HOME/.ssh/known_hosts"
          ssh-keyscan -T 10 -H 16.170.246.73  >> "$HOME/.ssh/known_hosts"
          ssh-keyscan -T 10 -H 13.60.163.72   >> "$HOME/.ssh/known_hosts"
          chmod 600 "$HOME/.ssh/known_hosts"

      - name: Run Ansible (K3s)
        run: |
          ansible-playbook \
            -i ansible/inventories/staging/inventory.ini \
            --private-key "$HOME/.ssh/id_rsa" \
            ansible/install-k3s.yml

  setup-prod:
    if: github.event.inputs.target_env == 'prod'
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install ansible + sshpass
        run: sudo apt update && sudo apt install -y ansible sshpass

      - name: Add host key
        run: |
          mkdir -p "$HOME/.ssh"
          ssh-keyscan -T 10 -H ${{ secrets.SERVER_HOST }} >> "$HOME/.ssh/known_hosts"
          chmod 600 "$HOME/.ssh/known_hosts"

      - name: Run Ansible (Docker)
        run: |
          ansible-playbook \
            -i ansible/inventories/prod/inventory.ini \
            ansible/install-docker.yml \
            --extra-vars "ansible_password=$PROD_SSH_PASSWORD ansible_become_pass=$PROD_SSH_PASSWORD"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          PROD_SSH_PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD }}
